apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api
  name: api
spec:
  containers:
    - env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
      image: aboubakar940/workout-planner:latest
      name: workout-planner-api
      ports:
        - containerPort: 3000
          protocol: TCP
  restartPolicy: OnFailure
