version: '3.8'

services:
  api:
    image: aboubakar940/workout-planner:latest
    container_name: workout-planner-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure 