apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-planner-config
  namespace: workout-planner-api
data:
  # Variables d'environnement
  NODE_ENV: "development"
  API_PORT: "3000"
  
  # Configuration sous forme de fichier
  config.json: |
    {
      "database": {
        "host": "mongodb://localhost:27017",
        "name": "workout-planner"
      },
      "api": {
        "cors": true,
        "timeout": 30000
      }
    }

  # Ajoutez ici d'autres variables de configuration nécessaires 