apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: workout-planner-api
spec:
  schedule: "0 1 * * *"  # Tous les jours à 1h du matin
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo:latest
            command:
            - /bin/sh
            - -c
            - |
              mongodump --host=mongodb --port=27017 --db=workout-planner --archive=/backup/workout-planner-$(date +%Y%m%d).gz --gzip
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure 