apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: workout-planner-api
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-volumes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            target_label: node 