apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-planner-config
  namespace: workout-planner-api
data:
  # Variables d'environnement de base
  NODE_ENV: "production"
  API_PORT: "3000"
  PORT: "3000"
  
  # Configuration MongoDB
  MONGODB_URI: "mongodb://mongodb:27017/workout-planner"
  
  # Configuration API
  API_PREFIX: "/api/v1"
  CORS_ORIGIN: "*"
  RATE_LIMIT: "100"
  
  # Configuration JWT
  JWT_EXPIRES_IN: "1d"
  
  # Configuration Logger
  LOG_LEVEL: "info" 