name: Branch CI

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'feat/**'
      - 'release/**'
      - 'develop'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'feat/**'
      - 'release/**'
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  quality:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check code style
      run: |
        npm run format:check
        npm run lint

  test:
    needs: quality
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit

    - name: Run integration tests
      run: npm run test:integration

    - name: Generate coverage report
      run: npm run test:cov 