name: Deploy to Ovh VPS

on:
  workflow_run:
    workflows: ["CD"]
    types:
      - completed
  workflow_dispatch:


jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH and Deploy on VPS
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.TOKEN_VPS }}
          script: |
            echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | sudo -S docker pull ${{secrets.DOCKER_HUB_USERNAME}}/workout-planner:latest
            echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | sudo -S docker stack deploy --compose-file docker-compose.yml workout-planner
            echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | sudo -S docker service update --image ${{secrets.DOCKER_HUB_USERNAME}}/workout-planner:latest workout-planner-api


